# Values used for the deployed application.
replicaCount: 1
service:
  name: upp-next-video-mapper
env:
  APP_NAME: next-video-mapper
  Q_GROUP: nextVideoMapper
  Q_READ_TOPIC: NativeCmsPublicationEvents
  Q_WRITE_TOPIC: CmsPublicationEvents
